# Generated by Django 4.1.7 on 2023-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='123', upload_to='media/'),
            preserve_default=False,
        ),
    ]
